---
services:
  tsdb:
    container_name: tsdb
    image: timescale/timescaledb:latest-pg18
    restart: on-failure
    environment:
      PGDATA: /pgdata
      POSTGRES_PASSWORD: password
    volumes:
      - pg:/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  pg:
