---
services:
  pgdb:
    container_name: pgdb
    image: postgres:18.6-alpine3.24
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: local
    volumes:
      - pg:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg:
