package spot

var spots = []Spot{
	{
		Name:          "Ocean Beach",
		City:          "San Diego",
		State:         "California",
		Latitude:      32.7487318,
		Longitude:     -117.2583427,
		SpotType:      "ocean",
		BreakType:     "beach break",
		Facing:        "WSW",
		NearestBuoyID: "46086",
		TideStationID: "9410170",
		TidalRange:    ">2ft",
		Spec:          "Beach break with shifting sandbars. Mornings traditionally better than afternoons. Highly exposed spot — conditions are frequently rougher than forecasts suggest. Strong rip currents are common, especially with wind > 15 mph or during large swell. Exercise caution in strong wind regardless of direction. Best swell directions: NW to W; SW also works. Holds up to ~8ft — above that most sets close out across the entire beach. Very low or negative tides accelerate closeout tendency. Best season: November through February (NW groundswell season).",
		Meta:          map[string]any{},
	},
	{
		Name:          "Rincon Point",
		City:          "Carpinteria",
		State:         "California",
		Latitude:      34.3728477,
		Longitude:     -119.4984414,
		SpotType:      "ocean",
		BreakType:     "point break",
		Facing:        "SW",
		NearestBuoyID: "46053",
		TideStationID: "9411340",
		TidalRange:    ">2ft",
		Spec:          "Classic California point break, known as the 'Queen of the Coast.' Optimal swell: WNW to W (250–280°), 4–8ft, 13s+ period. Key nuance: Rincon breaks significantly smaller than nearby spots when NW swell period is very long (>16s) — the swell wraps around the point and loses energy; conditions improve when period drops below 16s or swell shifts more WSW. All three sections (The Point, Rivermouth, Indicator) improve as the tide drops. Best at low to mid falling tide. Offshore wind: NE. Best season: October through March (west/northwest groundswell season).",
		Meta:          map[string]any{},
	},
	{
		Name:          "Empire Beach",
		City:          "Empire",
		State:         "Michigan",
		Latitude:      44.8120363,
		Longitude:     -86.1093288,
		SpotType:      "lake",
		BreakType:     "beach break",
		Facing:        "W",
		NearestBuoyID: "BSBM4",
		TideStationID: "N/A",
		TidalRange:    "N/A",
		Spec:          "W/NW winds produce ~60 miles of fetch — small to moderate waves. S/SW winds produce 250+ miles of fetch across the full length of Lake Michigan — best swell quality with longer periods and larger wave heights. Best conditions come from sustained S/SW winds at 15+ mph for 2+ days. Summer surfing is generally inconsistent; fall through early spring is the prime season.",
		Meta:          map[string]any{},
	},
	{
		Name:          "Stoney Point",
		City:          "Duluth",
		State:         "Minnesota",
		Latitude:      46.9666696,
		Longitude:     -91.6359906,
		SpotType:      "lake",
		BreakType:     "point break",
		Facing:        "SSE",
		NearestBuoyID: "SLVM5",
		TideStationID: "N/A",
		TidalRange:    "N/A",
		Spec:          "Rocky point break on the MN North Shore of Lake Superior. Lake surf depends entirely on wind-generated swell — there is no groundswell. Requires 2-3 days of sustained NE or NW winds at 15+ mph to build surfable waves. Classic pattern: NE/N winds (onshore) build waves across the lake, then a shift to NW (offshore) cleans up the faces. Gale warnings (34-47 knots) issued for western Lake Superior are a strong positive signal — prime surf conditions. Storm warnings (48+ knots) can produce 6-8ft+ waves but may be dangerous even for experienced surfers. 4-6ft waves are ideal. No tidal influence. Best season: late fall and winter when low-pressure systems produce frequent gales.",
		Meta:          map[string]any{},
	},
}
